services:
  server1:
    build:
      context: .
      dockerfile: DockerfileServer
      args:
        SERVER_FILE: servers/server1.go
        SERVER_PORT: 8082
    stdin_open: true
    tty: true
    ports:
      - "8082:8082"
    networks:
      - mynet
    environment:
      - CONFIG=${CONFIG}
    env_file:
      - .env

  server2:
    build:
      context: .
      dockerfile: DockerfileServer
      args:
        SERVER_FILE: servers/server2.go
        SERVER_PORT: 8083
    stdin_open: true
    tty: true
    ports:
      - "8083:8083"
    networks:
      - mynet
    environment:
      - CONFIG=${CONFIG}
    env_file:
      - .env

  server3:
    build:
      context: .
      dockerfile: DockerfileServer
      args:
        SERVER_FILE: servers/server3.go
        SERVER_PORT: 8084
    stdin_open: true
    tty: true
    ports:
      - "8084:8084"
    networks:
      - mynet
    environment:
      - CONFIG=${CONFIG}
    env_file:
      - .env

  client:
    build:
        context: .
        dockerfile: DockerfileClient
    stdin_open: true
    tty: true
    depends_on:
      - server1
      - server2
      - server3
    ports:
      - "8080:8080"
    networks:
      - mynet
    env_file:
      - .env

networks:
  mynet:
    driver: bridge
